name: Cucumber CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - uses:
          AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v95.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Make chromedriver executable
        run: chmod +x lib/chromedriver
      - name: test gradle
        run: ./gradlew cucumber || true

